---
- name: Install apache
  package:
    name: httpd
    state: present

- name: Enable service at startup
  service:
    name: httpd
    state: started
    enabled: yes

- name: Create site root
  file:
    path: "/var/www/html"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'